= Docker and OpenShift Issues

With the continual updating of docker without backwards compatibility has really
put many systems in a quandary. This project is one example of a workaround
specifically for OpenShift.

== Vagrant

. Start box
[source,bash]
----
$ vagrant up
----

== Build Docker images via 1.8.2 engine
SSH onto vagrant box

.indigo-ros-core
[source,bash]
----
$ cd /vagrant/docker/indigo-ros-core
$ sudo docker build -t jmarley/indigo-ros-core:docker1.8 .
$ sudo docker push
----

.indigo-ros-base
[source,bash]
----
$ sudo docker build -t jmarley/indig-ros-base:docker1.8 .
----

== OpenShift Setup

.Add Service Account
[source,bash]
----
$ oc create -f openshift/serviceaccount.yaml
----

.Add Security Control Context
[source,bash]
----
$ oc create -f openshift/scc_ros.yaml
----

.Update scc policy changes
[source,bash]
----
$ oc adm policy add-scc-to-user scc-ros <user> -n <project>
----

.Create image streams
[source,bash]
----
$ oc create -f openshift/imagestream-indigo-ros-base.yaml
$ oc create -f openshift/imagestream-docker-openshift-issues.yaml
----

.Create Build configurations
[source,bash]
----
$ oc create -f openshift/buildconfig-docker-openshift-issues.yaml
----

.Create Deploy configuraitons
[source,bash]
----
$ oc create -f openshift/deployconfig-docker-openshift-issues.yaml
----



== Working Environment

. added robot read in quay
. added .docker/config.json with creds
. updated BuildConfig.yaml
. rebuild images in 1.8 docker engine

== Status

image:https://quay.io/repository/jmarley/docker-openshift-issues/status?token=63177300-1b6e-4d19-8cb9-70fa010ec833["Docker Repository on Quay", link="https://quay.io/repository/jmarley/docker-openshift-issues"]

== References
. https://github.com/osrf/docker_images/tree/e4ba7284358c569ebb7818b85e8520fbe9157269/ros/indigo[ROS source]
. https://hub.docker.com/r/library/ros/[ROS on dockerhub]
. https://access.redhat.com/solutions/2347521[Red Hat Article on downgrading Docker]
. https://access.redhat.com/solutions/2168181[Red Hat Article on setting elevated privileges]
