apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: docker-openshift-issues
    name: indigo-ros-base
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: jmarley/indigo-ros-base:latest
      from:
        kind: DockerImage
        name: quay.io/jmarley/indigo-ros-base:latest
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: docker-openshift-issues
    name: docker-openshift-issues
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: docker-openshift-issues
    name: docker-openshift-issues
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: docker-openshift-issues:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: master
        uri: https://github.com/jmarley/docker-openshift-issues.git
      secrets: []
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: indigo-ros-base:latest
      type: Docker
    triggers:
    - github:
        secret: WUdulcszLu91zxIeuLa4
      type: GitHub
    - generic:
        secret: 8tbhsOm03nipbYa5bmqH
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: docker-openshift-issues
    name: docker-openshift-issues
  spec:
    replicas: 1
    selector:
      app: docker-openshift-issues
      deploymentconfig: docker-openshift-issues
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/container.docker-openshift-issues.image.entrypoint: '["/ros_entrypoint.sh","bash"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: docker-openshift-issues
          deploymentconfig: docker-openshift-issues
      spec:
        containers:
        - image: docker-openshift-issues:latest
          name: docker-openshift-issues
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - docker-openshift-issues
        from:
          kind: ImageStreamTag
          name: docker-openshift-issues:latest
      type: ImageChange
  status: {}
kind: List
metadata: {}
