apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: docker-openshift-issues
  name: docker-openshift-issues
spec:
  output:
    to:
      kind: ImageStreamTag
      name: docker-openshift-issues:latest
  postCommit: {}
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/jmarley/docker-openshift-issues.git
    secrets: []
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: indigo-ros-base:docker1.8
    type: Docker
  triggers:
  - github:
      secret: WUdulcszLu91zxIeuLa4
    type: GitHub
  - generic:
      secret: 8tbhsOm03nipbYa5bmqH
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
