apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: docker-openshift-issues
  name: docker-openshift-issues
spec: {}
status:
  dockerImageRepository: ""
