kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-ros
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:<project-name>:rossvcacct
- admin
groups:
- system:cluster-admins
- system:nodes
